services:
  - type: web
    name: mine-banco
    env: python
    buildCommand:|
      pip install --upgrade pip
      pip install -r deploy_banco/requirements.txt
    
    startCommand: gunicorn deploy_banco.app:app

